### ISSUE TITLE
Carga do histórico da loteca

### ISSUE THREAD

**Issue by viniciustsantos** [viniciustsantos/loteca-wordpress#17]
O histórico dos jogos, dos resultados e premiações precisa de uma carga inicial quando o plugin é instalado, esse procedimento pode ser demorado então deve ser incluído alerta após a ativação do plugin para que o administrador entre na página de administração do plugin e acione o processo.
Este processo deve fazer o download da planilha disponível no site da CEF e em seguida ler e inserir na base de resultados e rodadas.
Os times de cada jogo não são fornecidos no arquivo é necessário identificar o link que faça acesso direto aos resultados e utilizar o processo atual para leitura da página e captura dos jogos.
O ideal é que esse processo seja iniciado por ajax para não prender a página do administrador e um log seja gravado para que possa ser acompanhado.

**Comment by diegoBSousa** [comment]
Este plugin ainda funciona?

**Comment by viniciustsantos** [comment]
Diego,

Esta versão não deve estar funcionando, pois o site da CEF sofreu algumas
alterações, assim que puder vou atualizar e te aviso, já tenho uma versão
mais atualizada.

Mas se quiser fazer alguns testes posso lhe passar o site onde está sendo
usado.

Att,

Vinicius

Em 07/11/2016 23:11, "Diego Brito Sousa" <notifications@github.com>
escreveu:

**Comment by viniciustsantos** [comment]
Carreguei uma nova versão. abraço.
